### ISSUE TITLE
.scrapeUserPage() not working on Ubuntu Bionic

### ISSUE THREAD

**Issue by aymather** [rzlyp/instagram-scraping#17]
I am making a basic request to scrape "joerogan" from instagram like this:

```
const instagram = require('instagram-scraping');

const index = async () => {
	try {
		
		const { medias } = await instagram.scrapeUserPage('joerogan');
		console.log(medias);

	} catch (err) {
		console.log(err);
		return
	}
}

index();
```

Everything works correctly on my local mac, but when I push it to my ubuntu server I get the following error:

```
Error: Error scraping user page "joerogan"
    at Request._callback (/var/www/ViralDashboardApi/node_modules/instagram-scraping/index.js:43:24)
    at Request.self.callback (/var/www/ViralDashboardApi/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/var/www/ViralDashboardApi/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/var/www/ViralDashboardApi/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

This is the configuration of my ubuntu server:

```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

My first guess would be that my ubuntu server is missing some dependency, but I don't know what that would be. Other than that, I'm pretty lost 🤷🏻‍♂️

**Comment by aymather** [comment]
So I think the problem might be a redirect on the request to the HTML page. The response from my local mac (where it works normally) parses out these fields which contains the correct `ProfilePage` to the `entry_data` field.

```
config: {
    csrf_token: 'FoZig0eXgQmesbmxw5u7Wgq2QwAXqZHv',
    viewer: null,
    viewerId: null
  },
  country_code: 'US',
  language_code: 'en',
  locale: 'en_US',
  entry_data: { ProfilePage: [ [Object] ] },
  hostname: 'www.instagram.com',
  is_whitelisted_crawl_bot: false,
  deployment_stage: 'c2',
  ...
```
With the correct `entry_data` field: 
```
{
  ProfilePage: [
    {
      logging_page_id: 'profilePage_31357503',
      show_suggested_profiles: false,
      show_follow_dialog: false,
      graphql: [Object],
      toast_content_on_load: null
    }
  ]
}
```

However, when I run it from my ubuntu server (where it is NOT working), it's returning this:
```
config: {
    csrf_token: 'FO4hOy37xZRUKhMrtb9eFVE6HiP2mMqh',
    viewer: null,
    viewerId: null
  },
  country_code: 'US',
  language_code: 'en',
  locale: 'en_US',
  entry_data: { LoginAndSignupPage: [ [Object] ] },
  hostname: 'www.instagram.com',
  is_whitelisted_crawl_bot: false,
  deployment_stage: 'c2',
  ...
```
With the incorrect `entry_data` field:
```
{
  LoginAndSignupPage: [
    {
      captcha: [Object],
      gdpr_required: false,
      tos_version: 'row',
      username_hint: ''
    }
  ]
}
```

**Comment by shiraishimai** [comment]
Hi @aymather ,
I'm facing the same issue with my own solution, where I came here for alternatives,
I found Instagram has some other mechanisms to determine whether a request is from a bot.
I also wanted to bypass this check but had no luck.

**Comment by aymather** [comment]
@rzlyp any intension to look into this?

**Comment by marcelc63** [comment]
I'm having the same issues here. Working on local but not on Ubuntu.

I have tried giving the request user agent, cookies, and everything else to make it look like a user's request but no luck.

**Comment by aymather** [comment]
I spun up a MacOS server and made an api that's sitting on it to handle it and it works fine from there. I have a suspicion that the problem was that instagram started flagging activity from the server the requests were coming from and banned it. I guess only time will tell, but shouldn't there be a better way to mask these requests anyway?

**Comment by marcelc63** [comment]
@aymather if that's the case, perhaps it's worth trying to try to mask the request using a proxy. Since same as you, request I did from local works well.

**Comment by aymather** [comment]
@marcelc63 I ended up setting up my scraper on a different server and it seemed to work there at first. Then, after a couple days of running it on a CRON job, it started no longer working. I think Instagram was detecting my requests as a bot and banned them. I tried masking requests with the `tor-request` library but none, weirdly, all those requests were also blocked. If you find a reliable way of making the requests, please let me know!

**Comment by marcelc63** [comment]
@aymather I will keep you updated. I'm going to try set up a proxy and pass my request through it. Found a cheap proxy provider. I'll let you know if it work or not.

**Comment by aymather** [comment]
@marcelc63 did you ever link this package up with a proxy and get it to work?
