### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by KyleGoslan** [rzlyp/instagram-scraping#19]
Has instagram changed something, this no longer seems to be working? 

```
var ig = require('instagram-scraping');

ig.scrapeTag('veranda').then(result => {
  console.dir(result);
});
```

This now returns a rejected promise.

**Comment by froquede** [comment]
The account is private.

**Comment by KyleGoslan** [comment]
> The account is private.

What do you mean?

**Comment by froquede** [comment]
> What do you mean?

Sorry, i was checking the user method, it seems that instagram doesn't like this type of request and after a pattern of requests it gets identified as a bot.

https://github.com/rzlyp/instagram-scraping/issues/17#issuecomment-645994241

**Comment by KyleGoslan** [comment]
I'm no longer get any response. It looks like Instagram have now stopped the comments being loaded on tag pages: [https://www.instagram.com/explore/tags/beach/]( https://www.instagram.com/explore/tags/beach/)

Possibly causing the parsing to fail and the promise being rejected?
