### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by fazaio** [rzlyp/instagram-scraping#20]
Thanks for this package sir.
I use FastifyJs, its work and give me result.

but i got some log error :
`An error occurred calling scrapePostPage inside deepScrapeTagPage:TypeError: Cannot read property 'has_public_page' of null`

**Comment by gianpaj** [comment]
can you post the JS code that runs `scrapePostPage()`? thanks and possibly with the post you were trying to scrape?
