### ISSUE TITLE
 Get post info 

### ISSUE THREAD

**Issue by 89z** [rzlyp/instagram-scraping#26]
If I have a post such as this:

https://www.instagram.com/p/CT-cnxGhvvO/

How do I get the info for this post? Sorry for the basic question, but I have looked over the API and am not seeing a way to do this.

**Comment by restyler** [comment]
I would suggest you to extract shortcode from url ( it goes right after /p/ part ) and then use `scrapePostCode()`

**Comment by restyler** [comment]
Something like this:

```js
const ig = require('instagram-scraping')

let url = new URL(yourUrl)
let path = url.pathname.split('/')
if (!['p', 'tv', 'reel'].includes(path[1]) || !path[2] || !path[2].length) {
   throw new Error('invalid post url!')
}

let postId = path[2]
ig.scrapePostCode(postId).then((result) => { console.log(result) } )
```

**Comment by 89z** [comment]
This code works for me:

~~~js
const ig = require('instagram-scraping');
let postID = 'CT-cnxGhvvO';

ig.scrapePostCode(postID).then(
   result => console.log(result)
);
~~~

thanks for the help!
