### ISSUE TITLE
Custom proxy

### ISSUE THREAD

**Issue by WardenCommander** [rzlyp/instagram-scraping#28]
Hello great project,
can you add option for custom proxies? I already have list of proxies that im using and would love option to use them with this project.

**Comment by rzlyp** [comment]
i'm really sorry, if you don't mind, can you please collaborate to develop
this module?

currently, I don't have enough time to maintain this module.

**Comment by WardenCommander** [comment]
Im not really good at developing from start, I usually do just my hobby projects. I dont even know how i would integrate proxy into your project.
