### ISSUE TITLE
make new release and submit it to npm

### ISSUE THREAD

**Issue by gianpaj** [rzlyp/instagram-scraping#5]
The last commit adds the ability to "scrape users pages" https://github.com/rzlyp/instagram-scraping/commit/d9af23ba26361bbc852593c02795a8357a736d1a (Jun 2018)

But the last version 1.0.2 was published in Feb 2018:
https://www.npmjs.com/package/instagram-scraping

PS: thanks for making this. Scraping the meta-tags makes life so much easier! 🎉

**Comment by rzlyp** [comment]
thank you for your feedback :)

**Comment by rzlyp** [comment]
@gianpaj I already push the new release to the npm, thank you.

**Comment by gianpaj** [comment]
no problem. I've been using your package and extending it a bit.

OT question: Would it be easy to paginate through the user's post? I know we're scraping the `_sharedData` JSON object that appears in the HTML document.
For example, I would like to get the last 50 posts for a specific user. At the moment I'm getting only 12.
Thanks

**Comment by rzlyp** [comment]
Hi @gianpaj ,  yup, i will try to figure out for this case, i think it because instagram using pagination, 

i'll try to make updates for this case, so we can fetch all of the user posts.

Thank you.

**Comment by gianpaj** [comment]
Awesome! I'll try to make a PR to bring back so of my changes. For example a `scrapeUserPageDeep()` method.

As the current `scrapeUserPage()` doesn't return all the images of a post for a user. It just returns the first image, but I needed to scrape all the images of albums as well 😇
