### ISSUE TITLE
Continue scraping posts if there's an error

### ISSUE THREAD

**Issue by gianpaj** [rzlyp/instagram-scraping#7]
At the moment if the `scrapePostCode()` fails because there was any kind of issue while scraping a post (e.g. network issue), it won't return the successful ones.

**Comment by rzlyp** [comment]
@gianpaj yup, sorry i forgot to put the error handler in scrapePostCode() function.

I already push the new updates, and i still working on loading all media from the user page.

**Comment by gianpaj** [comment]
Thanks for the update.

I was thinking something more like this:

```diff
@@ -75,12 +75,12 @@ exports.scrapeUserPageDeep = function(username) {
         data.entry_data.ProfilePage[0].graphql.user.edge_owner_to_timeline_media.count > 0 &&
         data.entry_data.ProfilePage[0].graphql.user.edge_owner_to_timeline_media.edges
       ) {
         var edges = data.entry_data.ProfilePage[0].graphql.user.edge_owner_to_timeline_media.edges;
        var promises = Promise.map(edges, function(edge, i, len) {
           exports
             .scrapePostCode(edge.node.shortcode)
             .then(postPage => exports.preparePostFields(postPage))
             .catch(err => {
               console.log('An error occurred calling scrapePostPage inside deepScrapeTagPage' + ':' + err);
@@ -508,9 +508,11 @@ exports.deepScrapeTagPage = function(tag) {
             })
             .catch(function(err) {
               console.log('An error occurred calling scrapePostPage inside deepScrapeTagPage' + ':' + err);
+              return err;
             });
         })
           .then(function() {
+            tagPage.media = tagPage.media.filter(media => media.filter(result => !(result instanceof Error)));
             resolve(tagPage);
           })
           .catch(function(err) {
@@ -669,6 +671,6 @@ var scrape = function(html) {
   return json;
 };
```

This should filter out IG posts that returned an Error.

BTW: we should add testing and mock the requests to test these edge cases better. Maybe we can use [nock](https://github.com/nock/nock)

**Comment by rzlyp** [comment]
Hi, @gianpaj do you want to join develop this module? I'll add you as a collaborator if you want, or you can make a pull request for a specific update, and i'll publish it to NPM.

I'm a little bit busy at this time, so I can't solve your issues.

thank you.

**Comment by gianpaj** [comment]
Sure. I can't guarantee you a lot of time but would love to help the open-source community as a whole and improve this package.

**Comment by rzlyp** [comment]
@gianpaj I already invited you, thanks for joining to develop this package :).

https://github.com/rzlyp/instagram-scraping/invitations
